#!/bin/bash
SCRIPT_DIR="$(dirname "$0")/scripts"
selected_script=$(ls "$SCRIPT_DIR" | dmenu -p "Choose LED Matrix Design" "$@")
if [ "$selected_script" == '' ]; then exit 10; fi
$SCRIPT_DIR/$selected_script